apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: krakend-auth-route
  namespace: default
spec:
  parentRefs:
    - name: gateway       # Your Gateway resource in default namespace
      namespace: default
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/logintoken
      backendRefs:
        - name: apigateway  # The ClusterIP Service for KrakenD
          port: 8001
